DROP TABLE IF EXISTS `storage`;
CREATE TABLE `storage` (
    `id` int(11) NOT NULL auto_increment COMMENT '自增ID',
    `order_id` int(11) NOT NULL COMMENT '订单ID',
    `buyer_id` int(11) NOT NULL COMMENT '买手ID',
    `user_id` int(11) NOT NULL COMMENT '买家ID',
    `pack_id` int(11) NOT NULL COMMENT '包裹ID',
    `logistic_id` int(11) NOT NULL COMMENT '国内物流ID',
    `location` varchar(16) NOT NULL COMMENT '货架号',
    `memo` text NOT NULL COMMENT '库存备忘',
    `status` varchar(16) DEFAULT 'waiting' COMMENT '库存状态, waiting-未到货；in-已收货；out-已发货；canceled-已取消',
    `stock_status` varchar(16) DEFAULT 'normal' COMMENT '商品状态，normal-正常件；pending-问题件',
    `create_time` int(11) DEFAULT NULL COMMENT '库存登记时间',
    `pending_time` int(11) DEFAULT NULL COMMENT '问题件登记时间',
    `cs_status` smallint DEFAULT '0' COMMENT '客服状态，0-未处理；1-买家接受；2-买家不接受',
    `cs_memo` varchar(64) DEFAULT '' COMMENT '客服备忘',
    `cs_time` int(11) DEFAULT NULL COMMENT '客服处理时间',
    `pu_status` smallint DEFAULT '0' COMMENT '采购状态，0-未处理；1-接受入库；2-退回买手；3-销毁；4-买手补发；5-不再补发',
    `pu_memo` varchar(64) DEFAULT '' COMMENT '采购备忘',
    `pu_time` int(11) DEFAULT NULL COMMENT '采购处理时间',
    `in_time` int(11) DEFAULT NULL COMMENT '收货时间',
    `out_time` int(11) DEFAULT NULL COMMENT '发货时间',
    `action_time` int(11) DEFAULT NULL COMMENT '处理时间',
    `send_time` int(11) DEFAULT NULL COMMENT '采购发货时间',
    PRIMARY KEY (`id`),
    KEY `order_id_index` (`order_id`),
    KEY `buyer_id_index` (`buyer_id`),
    KEY `user_id_index` (`user_id`),
    KEY `pack_id_index` (`pack_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='库存管理';

