insert into `permission` (name, description, create_time) values('storage', '库存管理读', unix_timestamp()),('storage_w', '库存管理写', unix_timestamp());
insert into `action` (name, description, permission_id, create_time, update_time) select 'storage_index', '', id, unix_timestamp() , unix_timestamp() from permission where name='storage';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storage_read', '', id, unix_timestamp() , unix_timestamp() from permission where name='storage';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storage_search', '', id, unix_timestamp() , unix_timestamp() from permission where name='storage';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storage_select', '', id, unix_timestamp() , unix_timestamp() from permission where name='storage';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storage_select_search', '', id, unix_timestamp() , unix_timestamp() from permission where name='storage';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storage_create', '', id, unix_timestamp() , unix_timestamp() from permission where name='storage_w';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storage_update', '', id, unix_timestamp() , unix_timestamp() from permission where name='storage_w';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storage_delete', '', id, unix_timestamp() , unix_timestamp() from permission where name='storage_w';
insert into `permission` (name, description, create_time) values('storagecspending', '问题件买家处理读', unix_timestamp()),('storagecspending_w', '问题件买家处理写', unix_timestamp());
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagecspending_index', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagecspending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagecspending_read', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagecspending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagecspending_search', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagecspending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagecspending_select', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagecspending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagecspending_select_search', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagecspending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagecspending_create', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagecspending_w';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagecspending_update', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagecspending_w';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagecspending_delete', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagecspending_w';
insert into `permission` (name, description, create_time) values('storagepurchasepending', '问题件买手处理读', unix_timestamp()),('storagepurchasepending_w', '问题件买手处理写', unix_timestamp());
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagepurchasepending_index', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagepurchasepending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagepurchasepending_read', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagepurchasepending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagepurchasepending_search', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagepurchasepending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagepurchasepending_select', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagepurchasepending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagepurchasepending_select_search', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagepurchasepending';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagepurchasepending_create', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagepurchasepending_w';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagepurchasepending_update', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagepurchasepending_w';
insert into `action` (name, description, permission_id, create_time, update_time) select 'storagepurchasepending_delete', '', id, unix_timestamp() , unix_timestamp() from permission where name='storagepurchasepending_w';

alter table `storage` add column `imgs` text COMMENT '问题拍照';
